arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]

# conda-forge only supports cross-compiling with CUDA 11.2

cuda_compiler:
  - nvcc

docker_image:                                  # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
   - quay.io/condaforge/linux-anvil-cuda:11.2  # [(aarch64 or ppc64le) and os.environ.get("BUILD_PLATFORM") == "linux-64"]

c_compiler_version:        # [linux]
  - 10                     # [aarch64 or ppc64le]

cxx_compiler_version:      # [linux]
  - 10                     # [aarch64 or ppc64le]

fortran_compiler_version:  # [linux]
  - 10                     # [aarch64 or ppc64le]

cuda_compiler_version:
  - 11.2                   # [aarch64 or ppc64le]

cudnn:
  - 8                      # [aarch64 or ppc64le]

cdt_name:  # [linux]
  - cos7   # [aarch64 or ppc64le]

c_compiler:                    # [win]
  - vs2017                     # [win]
cxx_compiler:                  # [win]
  - vs2017                     # [win]
