arm_variant_type:          # [aarch64]
  - sbsa                   # [aarch64]

docker_image:                                    # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
   - quay.io/condaforge/linux-anvil-cos7-x86_64  # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]

c_compiler_version:        # [linux]
  - 10                     # [linux64]

cxx_compiler_version:      # [linux]
  - 10                     # [linux64]

fortran_compiler_version:  # [linux]
  - 10                     # [linux64]

cuda_compiler:
  - cuda-nvcc

cuda_compiler_version:
  - 12.0

cudnn:
  - None

cdt_name:                  # [linux]
  - cos7                   # [linux64]
