c_stdlib_version:                                   # [linux]
  - 2.17                                            # [linux]
  - 2.17                                            # [linux]
  - 2.17                                            # [linux]
docker_image:                                       # [linux]
  - quay.io/condaforge/linux-anvil-cos7-x86_64      # [linux]
  - quay.io/condaforge/linux-anvil-cuda:11.8        # [linux]
  - quay.io/condaforge/linux-anvil-alma-x86_64:8    # [linux]
# rest just to make smithy happy
c_compiler_version:                                 # [linux]
  - 13                                              # [linux]
  - 11                                              # [linux]
  - 12                                              # [linux]
cxx_compiler_version:                               # [linux]
  - 13                                              # [linux]
  - 11                                              # [linux]
  - 12                                              # [linux]
fortran_compiler_version:                           # [linux]
  - 13                                              # [linux]
  - 11                                              # [linux]
  - 12                                              # [linux]
cdt_name:                                           # [linux]
  - cos7                                            # [linux]
  - cos7                                            # [linux]
  - cos7                                            # [linux]
cuda_compiler:                                      # [linux]
  - None                                            # [linux]
  - nvcc                                            # [linux]
  - cuda-nvcc                                       # [linux]
cuda_compiler_version:                              # [linux]
  - None                                            # [linux]
  - 11.8                                            # [linux]
  - 12.6                                            # [linux]
